<a href="https://colab.research.google.com/github/lovely-deoghariya/100-days-SQL-Journey/blob/main/Day02_SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import pandas as pd

In [ ]:
conn = sqlite3.connect("/content/drive/MyDrive/SQL/company.db")

In [ ]:
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

          name
0  departments
1    employees
2     products
3    customers
4       orders

In [ ]:
#Display only department_name from department
pd.read_sql("""
SELECT department_name
FROM departments;
""", conn)

    department_name
0                HR
1           Finance
2                IT
3         Marketing
4             Sales
5        Operations
6           Support
7             Legal
8  Data Engineering
9          Security

In [ ]:
#Display only product_name and print product
pd.read_sql("""
SELECT product_name
FROM products;
""", conn)

          product_name
0       Laptop Model 1
1       Laptop Model 2
2       Laptop Model 3
3       Laptop Model 4
4       Mobile Model 1
5       Mobile Model 2
6       Mobile Model 3
7       Mobile Model 4
8   Headphones Model 1
9   Headphones Model 2
10  Headphones Model 3
11  Headphones Model 4
12     Monitor Model 1
13     Monitor Model 2
14     Monitor Model 3
15     Monitor Model 4
16    Keyboard Model 1
17    Keyboard Model 2
18    Keyboard Model 3
19    Keyboard Model 4
20       Mouse Model 1
21       Mouse Model 2
22       Mouse Model 3
23       Mouse Model 4
24      Camera Model 1

In [ ]:
#Display all unique city values from customers
pd.read_sql("""
SELECT DISTINCT city
FROM customers;
""", conn)

        city
0  Bangalore
1     Mumbai
2    Chennai
3       Pune
4  Hyderabad
5      Delhi
6    Kolkata

In [ ]:
#Display all unique job_tittle values from employees
pd.read_sql("""
SELECT DISTINCT job_title
FROM employees;
""", conn)

             job_title
0         HR Executive
1           Accountant
2    Software Engineer
3  Marketing Executive
4      Sales Executive
5   Operations Analyst
6     Support Engineer
7        Legal Advisor
8        Data Engineer
9     Security Analyst

In [ ]:
#Display only first_name, last_name and email from employees
pd.read_sql("""
SELECT first_name, last_name, email
FROM employees;
""", conn)

   first_name last_name                       email
0       Aarav     Patel    aarav.patel1@company.com
1      Vivaan     Patel   vivaan.patel2@company.com
2      Aditya       Das     aditya.das3@company.com
3        Riya       Das       riya.das4@company.com
4       Priya       Das      priya.das5@company.com
5        Neha    Taylor    neha.taylor6@company.com
6       Rahul       Roy      rahul.roy7@company.com
7        Amit       Roy       amit.roy8@company.com
8        John     Brown     john.brown9@company.com
9        Emma     Kumar    emma.kumar10@company.com
10       Noah     Singh    noah.singh11@company.com
11     Olivia       Roy    olivia.roy12@company.com
12       Liam     Singh    liam.singh13@company.com
13     Sophia       Roy    sophia.roy14@company.com
14     Ananya     Singh  ananya.singh15@company.com
15      Karan    Taylor  karan.taylor16@company.com
16      Rohan     Singh   rohan.singh17@company.com
17      Sneha    Sharma  sneha.sharma18@company.com
18      David     Singh   david.singh19@company.com
19       Sara    Taylor   sara.taylor20@company.com
20      Arjun    Taylor  arjun.taylor21@company.com
21       Isha       Roy      isha.roy22@company.com
22      Kabir    Sharma  kabir.sharma23@company.com
23      Meera     Singh   meera.singh24@company.com
24     Vikram       Roy    vikram.roy25@company.com
25      Nisha    Sharma  nisha.sharma26@company.com
26     Daniel       Roy    daniel.roy27@company.com
27      Grace     Brown   grace.brown28@company.com
28      Aryan       Das     aryan.das29@company.com
29      Pooja    Sharma  pooja.sharma30@company.com

In [ ]:
#Display all unique product categories from the products table
pd.read_sql("""
SELECT DISTINCT category
FROM products;
""", conn)

     category
0      Laptop
1      Mobile
2  Headphones
3     Monitor
4    Keyboard
5       Mouse
6      Camera